//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class breakDate
    {
        public int breakID { get; set; }
        public Nullable<int> seasonID { get; set; }
        public Nullable<System.DateTime> breakDate1 { get; set; }
    
        public virtual Season Season { get; set; }
    }
}
