//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Club
    {
        public int clubID { get; set; }
        public int leaguePID { get; set; }
        public string clubName { get; set; }
        public string firstRegistered { get; set; }
        public int pContact { get; set; }
        public Nullable<int> sContact { get; set; }
        public int location { get; set; }
    }
}
