//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Division
    {
        public int divID { get; set; }
        public int leaguePID { get; set; }
        public string divCode { get; set; }
        public Nullable<int> ageLimit { get; set; }
    }
}
