//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Draw
    {
        public int drawID { get; set; }
        public int seasonPID { get; set; }
        public int divisionPID { get; set; }
        public Nullable<int> numFinalTeams { get; set; }
        public Nullable<int> finalsDrawPID { get; set; }
    }
}
