//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EDSL_dbEntities : DbContext
    {
        public EDSL_dbEntities()
            : base("name=EDSL_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__RefactorLog> C__RefactorLog { get; set; }
        public virtual DbSet<breakDate> breakDates { get; set; }
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<Division> Divisions { get; set; }
        public virtual DbSet<Draw> Draws { get; set; }
        public virtual DbSet<Leauge> Leauges { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Match> Matches { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Round> Rounds { get; set; }
        public virtual DbSet<Season> Seasons { get; set; }
        public virtual DbSet<Team> Teams { get; set; }
    }
}
