//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LadderPos
    {
        public int LadderPosId { get; set; }
        public int LadderID { get; set; }
        public int TeamID { get; set; }
        public int Played { get; set; }
        public int Wins { get; set; }
        public int losses { get; set; }
        public int draws { get; set; }
        public int goalsFor { get; set; }
        public int goalsAgainst { get; set; }
    
        public virtual Ladder Ladder { get; set; }
        public virtual Team Team { get; set; }
    }
}
