//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Leauge
    {
        public string leagueID { get; set; }
        public string leagueName { get; set; }
    }
}
