//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Location()
        {
            this.Clubs = new HashSet<Club>();
        }
    
        public int groundID { get; set; }
        public string groundName { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public int postCode { get; set; }
        public string suburb { get; set; }
        public string state { get; set; }
        public Nullable<int> homeClub { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Club> Clubs { get; set; }
        public virtual Club Club { get; set; }
    }
}
