//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public string groundID { get; set; }
        public string groundName { get; set; }
        public string addressLine1 { get; set; }
        public string addressLine2 { get; set; }
        public int postCode { get; set; }
        public string suburb { get; set; }
        public string state { get; set; }
        public string homeClub { get; set; }
    }
}
