//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public string playerID { get; set; }
        public string teamPID { get; set; }
        public string pContact { get; set; }
        public string eContact { get; set; }
        public Nullable<int> firstRegistered { get; set; }
    }
}
