//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDSL_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int playerID { get; set; }
        public int teamPID { get; set; }
        public int pContact { get; set; }
        public Nullable<int> eContact { get; set; }
        public Nullable<System.DateTime> firstRegistered { get; set; }
        public int age { get; set; }
        public System.DateTime birthDate { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Contact Contact1 { get; set; }
        public virtual Team Team { get; set; }
    }
}
